// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   string                 `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"` // JWT token
	Metadata      *AgentMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetCredentials() string {
	if x != nil {
		return x.Credentials
	}
	return ""
}

func (x *AuthRequest) GetMetadata() *AgentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AgentMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Engine        string                 `protobuf:"bytes,6,opt,name=engine,proto3" json:"engine,omitempty"`
	Organization  string                 `protobuf:"bytes,7,opt,name=organization,proto3" json:"organization,omitempty"`
	Machine       string                 `protobuf:"bytes,8,opt,name=machine,proto3" json:"machine,omitempty"`
	HideLlm       bool                   `protobuf:"varint,9,opt,name=hide_llm,json=hideLlm,proto3" json:"hide_llm,omitempty"`                     // when true, exclude this agent from /v1/models
	LlmPrettyName string                 `protobuf:"bytes,10,opt,name=llm_pretty_name,json=llmPrettyName,proto3" json:"llm_pretty_name,omitempty"` // human-readable display name (e.g. "xLAM 8B")
	LlmInfo       string                 `protobuf:"bytes,11,opt,name=llm_info,json=llmInfo,proto3" json:"llm_info,omitempty"`                     // short description (e.g. "A small model useful for FC")
	Capability    string                 `protobuf:"bytes,12,opt,name=capability,proto3" json:"capability,omitempty"`                              // "llm" (default), "embedding", or "reranker"
	GpuModel      string                 `protobuf:"bytes,13,opt,name=gpu_model,json=gpuModel,proto3" json:"gpu_model,omitempty"`                  // hardware identifier set by operator (e.g. "RTX4090", "RTX5090")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMetadata) Reset() {
	*x = AgentMetadata{}
	mi := &file_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetadata) ProtoMessage() {}

func (x *AgentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetadata.ProtoReflect.Descriptor instead.
func (*AgentMetadata) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AgentMetadata) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentMetadata) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *AgentMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentMetadata) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AgentMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AgentMetadata) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *AgentMetadata) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *AgentMetadata) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *AgentMetadata) GetHideLlm() bool {
	if x != nil {
		return x.HideLlm
	}
	return false
}

func (x *AgentMetadata) GetLlmPrettyName() string {
	if x != nil {
		return x.LlmPrettyName
	}
	return ""
}

func (x *AgentMetadata) GetLlmInfo() string {
	if x != nil {
		return x.LlmInfo
	}
	return ""
}

func (x *AgentMetadata) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *AgentMetadata) GetGpuModel() string {
	if x != nil {
		return x.GpuModel
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Libp2PInfo    *LibP2PInfo            `protobuf:"bytes,4,opt,name=libp2p_info,json=libp2pInfo,proto3" json:"libp2p_info,omitempty"`
	Config        *RouterConfig          `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *AuthResponse) GetLibp2PInfo() *LibP2PInfo {
	if x != nil {
		return x.Libp2PInfo
	}
	return nil
}

func (x *AuthResponse) GetConfig() *RouterConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type LibP2PInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibP2PInfo) Reset() {
	*x = LibP2PInfo{}
	mi := &file_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibP2PInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibP2PInfo) ProtoMessage() {}

func (x *LibP2PInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibP2PInfo.ProtoReflect.Descriptor instead.
func (*LibP2PInfo) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LibP2PInfo) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *LibP2PInfo) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *LibP2PInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type RouterConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatInterval int32                  `protobuf:"varint,1,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	RequestTimeout    int32                  `protobuf:"varint,2,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	MaxRequestSize    int32                  `protobuf:"varint,3,opt,name=max_request_size,json=maxRequestSize,proto3" json:"max_request_size,omitempty"`
	SessionTtl        int32                  `protobuf:"varint,4,opt,name=session_ttl,json=sessionTtl,proto3" json:"session_ttl,omitempty"` // seconds; 0 means use agent default (1h)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RouterConfig) Reset() {
	*x = RouterConfig{}
	mi := &file_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterConfig) ProtoMessage() {}

func (x *RouterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterConfig.ProtoReflect.Descriptor instead.
func (*RouterConfig) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RouterConfig) GetHeartbeatInterval() int32 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *RouterConfig) GetRequestTimeout() int32 {
	if x != nil {
		return x.RequestTimeout
	}
	return 0
}

func (x *RouterConfig) GetMaxRequestSize() int32 {
	if x != nil {
		return x.MaxRequestSize
	}
	return 0
}

func (x *RouterConfig) GetSessionTtl() int32 {
	if x != nil {
		return x.SessionTtl
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{5}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_auth_proto protoreflect.FileDescriptor

const file_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x10proto/auth.proto\x12\x0ehivenet_router\"j\n" +
	"\vAuthRequest\x12 \n" +
	"\vcredentials\x18\x01 \x01(\tR\vcredentials\x129\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1d.hivenet_router.AgentMetadataR\bmetadata\"\xf8\x02\n" +
	"\rAgentMetadata\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x16\n" +
	"\x06engine\x18\x06 \x01(\tR\x06engine\x12\"\n" +
	"\forganization\x18\a \x01(\tR\forganization\x12\x18\n" +
	"\amachine\x18\b \x01(\tR\amachine\x12\x19\n" +
	"\bhide_llm\x18\t \x01(\bR\ahideLlm\x12&\n" +
	"\x0fllm_pretty_name\x18\n" +
	" \x01(\tR\rllmPrettyName\x12\x19\n" +
	"\bllm_info\x18\v \x01(\tR\allmInfo\x12\x1e\n" +
	"\n" +
	"capability\x18\f \x01(\tR\n" +
	"capability\x12\x1b\n" +
	"\tgpu_model\x18\r \x01(\tR\bgpuModel\"\xda\x01\n" +
	"\fAuthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12;\n" +
	"\vlibp2p_info\x18\x04 \x01(\v2\x1a.hivenet_router.LibP2PInfoR\n" +
	"libp2pInfo\x124\n" +
	"\x06config\x18\x05 \x01(\v2\x1c.hivenet_router.RouterConfigR\x06config\"_\n" +
	"\n" +
	"LibP2PInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\xb1\x01\n" +
	"\fRouterConfig\x12-\n" +
	"\x12heartbeat_interval\x18\x01 \x01(\x05R\x11heartbeatInterval\x12'\n" +
	"\x0frequest_timeout\x18\x02 \x01(\x05R\x0erequestTimeout\x12(\n" +
	"\x10max_request_size\x18\x03 \x01(\x05R\x0emaxRequestSize\x12\x1f\n" +
	"\vsession_ttl\x18\x04 \x01(\x05R\n" +
	"sessionTtl\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xa6\x01\n" +
	"\vAuthService\x12I\n" +
	"\fAuthenticate\x12\x1b.hivenet_router.AuthRequest\x1a\x1c.hivenet_router.AuthResponse\x12L\n" +
	"\vHealthCheck\x12\x1d.hivenet_router.HealthRequest\x1a\x1e.hivenet_router.HealthResponseB\x16Z\x14hivenet_router/protob\x06proto3"

var (
	file_proto_auth_proto_rawDescOnce sync.Once
	file_proto_auth_proto_rawDescData []byte
)

func file_proto_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)))
	})
	return file_proto_auth_proto_rawDescData
}

var file_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_auth_proto_goTypes = []any{
	(*AuthRequest)(nil),    // 0: hivenet_router.AuthRequest
	(*AgentMetadata)(nil),  // 1: hivenet_router.AgentMetadata
	(*AuthResponse)(nil),   // 2: hivenet_router.AuthResponse
	(*LibP2PInfo)(nil),     // 3: hivenet_router.LibP2PInfo
	(*RouterConfig)(nil),   // 4: hivenet_router.RouterConfig
	(*HealthRequest)(nil),  // 5: hivenet_router.HealthRequest
	(*HealthResponse)(nil), // 6: hivenet_router.HealthResponse
}
var file_proto_auth_proto_depIdxs = []int32{
	1, // 0: hivenet_router.AuthRequest.metadata:type_name -> hivenet_router.AgentMetadata
	3, // 1: hivenet_router.AuthResponse.libp2p_info:type_name -> hivenet_router.LibP2PInfo
	4, // 2: hivenet_router.AuthResponse.config:type_name -> hivenet_router.RouterConfig
	0, // 3: hivenet_router.AuthService.Authenticate:input_type -> hivenet_router.AuthRequest
	5, // 4: hivenet_router.AuthService.HealthCheck:input_type -> hivenet_router.HealthRequest
	2, // 5: hivenet_router.AuthService.Authenticate:output_type -> hivenet_router.AuthResponse
	6, // 6: hivenet_router.AuthService.HealthCheck:output_type -> hivenet_router.HealthResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_auth_proto_init() }
func file_proto_auth_proto_init() {
	if File_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_proto = out.File
	file_proto_auth_proto_goTypes = nil
	file_proto_auth_proto_depIdxs = nil
}
